from Model.Helm import Helm

helme = {
    "Night Hawk": Helm("Night Hawk", "S", 7, 140, "Jethelm", "Ratsche", "Fiberglas"),
    "Falcon GT": Helm("Falcon GT", "M", 6, 270, "Klapphelm", "Doppel-D", "Carbon"),
    "Speed Demon": Helm("Speed Demon", "L", 5, 220, "Sport", "Ratsche", "Polycarbonat"),
    "Dirt Blazer": Helm("Dirt Blazer", "M", 4, 250, "Enduro", "Doppel-D", "Fiberglas"),
    "Sunset Cruiser": Helm("Sunset Cruiser", "XL", 3, 180, "Cruiser", "Ratsche", "Carbon"),
    "City Hawk": Helm("City Hawk", "S", 9, 130, "Jethelm", "Ratsche", "Polycarbonat"),
    "Elite Touring": Helm("Elite Touring", "M", 7, 280, "Klapphelm", "Doppel-D", "Fiberglas"),
    "Speed Viper": Helm("Speed Viper", "L", 6, 200, "Sport", "Ratsche", "Carbon"),
    "Enduro X": Helm("Enduro X", "M", 5, 260, "Enduro", "Doppel-D", "Polycarbonat"),
    "Thunder Cruiser": Helm("Thunder Cruiser", "XL", 4, 190, "Cruiser", "Ratsche", "Fiberglas"),
    "Street Rebel": Helm("Street Rebel", "S", 8, 120, "Jethelm", "Ratsche", "Polycarbonat"),
    "Globetrotter": Helm("Globetrotter", "M", 6, 270, "Klapphelm", "Doppel-D", "Carbon"),
    "Velocity Storm": Helm("Velocity Storm", "L", 5, 230, "Sport", "Ratsche", "Polycarbonat"),
    "Trail Master": Helm("Trail Master", "M", 4, 250, "Enduro", "Doppel-D", "Fiberglas"),
    "Blitz Racer": Helm("Blitz Racer", "L", 6, 200, "Sport", "Ratsche", "Carbon"),
    "Wild Roamer": Helm("Wild Roamer", "M", 5, 260, "Enduro", "Doppel-D", "Polycarbonat"),
    "Neon Speed": Helm("Neon Speed", "S", 8, 120, "Jethelm", "Ratsche", "Polycarbonat"),
    "Hyper Rider": Helm("Hyper Rider", "M", 5, 250, "Sport", "Ratsche", "Fiberglas"),
    "Desert Hawk": Helm("Desert Hawk", "L", 4, 240, "Enduro", "Doppel-D", "Carbon"),
    "Night Racer": Helm("Night Racer", "XL", 3, 200, "Cruiser", "Ratsche", "Polycarbonat"),
    "Comet Jet": Helm("Comet Jet", "S", 7, 110, "Jethelm", "Ratsche", "Fiberglas"),
    "Shadow Touring": Helm("Shadow Touring", "M", 6, 275, "Klapphelm", "Doppel-D", "Carbon"),
    "Lightning Speed": Helm("Lightning Speed", "L", 5, 225, "Sport", "Ratsche", "Polycarbonat"),
    "Speed Phantom": Helm("Speed Phantom", "M", 4, 210, "Sport", "Ratsche", "Fiberglas"),
    "Extreme Ride": Helm("Extreme Ride", "XL", 5, 260, "Enduro", "Doppel-D", "Carbon"),
    "Urban Explorer": Helm("Urban Explorer", "S", 6, 170, "Jethelm", "Ratsche", "Polycarbonat"),
    "Classic Heritage": Helm("Classic Heritage", "L", 3, 200, "Cruiser", "Ratsche", "Fiberglas"),
}
